#!/bin/bash
clia=/usr/local/bin/clia
nc=/bin/nc
echo=/bin/echo

$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="Trips by Truck" filter="tripLeg_id->truck_id = @Parameter:truck AND tripLeg_id->workshopTrip = \"0\" AND tripLeg_id->hollowTrip = \"false\" AND cargo_id->businessUnit_id IN @Parameter:businessUnit_id AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->loadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->loadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="Planner Trip Time Report" filter="cargo_id->businessUnit_id IN @Parameter:businessUnit_id AND cargo_id->customer_id = @Parameter:customer AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->loadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->loadingArrivalETA <= @Parameter:stopDate)) AND tripLeg_id->workshopTrip = \"0\" AND tripLeg_id->hollowTrip = \"false\""
$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="Trip Status Report" filter="tripLeg_id->workshopTrip = \"0\" AND cargo_id->businessUnit_id IN @Parameter:businessUnit_id AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->offloadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->offloadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="Outstanding Pallet Report" filter="cargo_id->customer_id = @Parameter:customer AND tripLeg_id->workshopTrip = \"0\" AND cargo_id->eHRNNumber = null AND cargo_id->palletType = \"PEN\" AND cargo_id->numberOfPalletsReturned > \"0\" AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->offloadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->offloadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="CPK Report" filter="cargo_id->customer_id = @Parameter:customer AND cargo_id->businessUnit_id IN @Parameter:businessUnit_id AND tripLeg_id->workshopTrip = \"0\" AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->offloadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->offloadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_TripLegCargo type="ItemListDataView" name="Invoice Report" filter="cargo_id->businessUnit_id IN @Parameter:businessUnit_id AND udo_cargo.customer_id = @Parameter:customer AND tripLeg_id->workshopTrip = \"0\" AND ((tripLeg_id->loadingArrivalTime != null AND tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND tripLeg_id->offloadingArrivalTime <= @Parameter:stopDate) OR (tripLeg_id->loadingArrivalTime = null AND tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND tripLeg_id->offloadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_Cargo type="ItemListDataView" name="Trips per Customer" filter="udo_TripLegCargo.cargo_id->tripLeg_id->workshopTrip = \"0\" AND udo_cargo.customer_id = @Parameter:customer AND udo_cargo.businessUnit_id IN @Parameter:businessUnit_id AND ((udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime != null AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime <= @Parameter:stopDate) OR (udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime = null AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_Cargo type="ItemListDataView" name="Trip Detail Report" filter="udo_TripLegCargo.cargo_id->tripLeg_id->workshopTrip = \"0\" AND udo_cargo.customer_id = @Parameter:customer AND businessUnit_id IN @Parameter:businessUnit_id AND ((udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime != null AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime <= @Parameter:stopDate) OR (udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime = null AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalETA >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalETA <= @Parameter:stopDate))"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_Cargo type="ItemListDataView" name="Trips to Invoice" filter="udo_TripLegCargo.cargo_id->tripLeg_id->workshopTrip = \"0\" AND udo_TripLegCargo.cargo_id->tripLeg_id->hollowTrip = \"0\" AND udo_cargo.customer_id = @Parameter:customer AND udo_cargo.businessUnit_id IN @Parameter:businessUnit_id AND (udo_TripLegCargo.cargo_id->tripLeg_id->loadingStarted != null AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingStarted >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingStarted <= @Parameter:stopDate) AND (udo_cargo.companyInvoiceNumber = \"\" OR udo_cargo.companyInvoiceNumber = null)"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_Cargo type="ItemListDataView" name="POD Turnaround" filter="udo_TripLegCargo.cargo_id->tripLeg_id->workshopTrip = \"0\" AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime >= @Parameter:startDate AND udo_TripLegCargo.cargo_id->tripLeg_id->loadingArrivalTime <= @Parameter:stopDate AND udo_cargo.customer_id = @Parameter:customer AND udo_cargo.businessUnit_id IN @Parameter:businessUnit_id"
$clia $TENANT_ID DataView setFilter objectRegistry=udo_Cargo type="ItemListDataView" name="Special-Needs Cargoes" filter="udo_TripLegCargo.cargo_id->tripLeg_id->hollowTrip = \"0\" AND udo_TripLegCargo.cargo_id->tripLeg_id->workshopTrip = \"0\" AND specialInstructions != null AND plannedLoadingArrivalDate >= @Parameter:startDate AND plannedLoadingArrivalDate <= @Parameter:stopDate AND udo_cargo.customer_id = @Parameter:customer AND businessUnit_id IN @Parameter:businessUnit_id"
$clia 0 Cache flush
$echo FLUSHALL | $nc localhost 6379
