#!/bin/bash
clia=/usr/local/bin/clia
TENANT_ID="0002"
clia $TENANT_ID DataView createItemList objectRegistry="udo_Cargo" name="Incomplete Trips by Fleet" internalCreator="Report" primaryOwner="Admin" primaryOwnerCrud="Create, Read, Update, Delete" groupOwner="Reports" groupOwnerCrud="Read"
clia $TENANT_ID DataView setShowOptions objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" detailAction="Open" showActions=0 showExport=1 showFooterBar=1
clia $TENANT_ID DataView setIcon objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" icon="icon-reports.gif"
clia $TENANT_ID DataView setPageSize objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" pageSize="1000" icon="icon-reports.gif"
clia $TENANT_ID DataView setNoRecordsMessage objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" message="No records found"
clia $TENANT_ID DataView setFilter objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" filter='loadingTripLeg_id->truck_id = @InterimResult:truck_id AND ((loadingTripLeg_id->loadingStarted = null AND loadingTripLeg_id->loadingArrivalETA >= @InterimResult:beginDate AND loadingTripLeg_id->loadingArrivalETA <= @InterimResult:endDate) AND (workshopTrip = "false" OR workshopTrip = "NULL") AND (hollowTrip = "false" OR hollowTrip = "NULL") AND (tripNumber = null) AND ((tripLegsCount = "1" AND loadingTripLeg_id->loadingStarted = null AND loadingTripLeg_id->loadingArrivalTime = null AND loadingTripLeg_id->loadingFinished = null AND loadingTripLeg_id->timeLeft = null AND loadingTripLeg_id->offloadingArrivalTime = null AND loadingTripLeg_id->offloadingStarted = null AND loadingTripLeg_id->offloadingCompleted = null AND loadingTripLeg_id->kmsBegin = null AND loadingTripLeg_id->kmsEnd = null) OR (tripLegsCount > "1" AND (loadingTripLeg_id->loadingStarted = null AND loadingTripLeg_id->loadingArrivalTime = null AND loadingTripLeg_id->loadingFinished = null AND loadingTripLeg_id->timeLeft = null AND loadingTripLeg_id->offloadingArrivalTime = null AND loadingTripLeg_id->offloadingStarted = null AND loadingTripLeg_id->offloadingCompleted = null AND loadingTripLeg_id->kmsBegin = null AND loadingTripLeg_id->kmsEnd = null) AND (offloadingTripLeg_id->loadingStarted = null AND offloadingTripLeg_id->loadingArrivalTime = null AND offloadingTripLeg_id->loadingFinished = null AND offloadingTripLeg_id->timeLeft = null AND offloadingTripLeg_id->offloadingArrivalTime = null AND offloadingTripLeg_id->offloadingStarted = null AND offloadingTripLeg_id->offloadingCompleted = null AND offloadingTripLeg_id->kmsBegin = null AND offloadingTripLeg_id->kmsEnd = null))))'
clia $TENANT_ID DataView setOrderBy objectRegistry="udo_Cargo" type="ItemListDataView" name="Incomplete Trips by Fleet" orderByField=id orderByDirection=ASC
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Trip Number" source="tripNumber"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Cargo ID" source="id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Order Number" source="orderNumber"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Invoice Number" source="companyInvoiceNumber"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Money Order Numbers" source="moneyOrderNumbers"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Customer" source="customer_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Driver" source="loadingTripLeg_id->driver_id->person_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Driver Detail" source="loadingTripLeg_id->driver_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="OCR?" source="hasImageGroup"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Syspro?" source="sysproOrderPlaced"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Truck" source="loadingTripLeg_id->truck_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Fleet" source="loadingTripLeg_id->truck_id->primaryFleet_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Trailer" source="loadingTripLeg_id->trailer_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Trip Legs" source="tripLegsCount"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Income" source="totalIncome"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Additional Charges" source="additionalCharges"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading ETA" source="loadingTripLeg_id->loadingArrivalETA"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Arrival" source="loadingTripLeg_id->loadingArrivalTime"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Started" source="loadingTripLeg_id->loadingStarted"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Finished" source="loadingTripLeg_id->loadingFinished"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Time Left" source="loadingTripLeg_id->timeLeft"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Offloading Arrival ETA" source="loadingTripLeg_id->offloadingArrivalETA"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Offloading Arrival" source="loadingTripLeg_id->offloadingArrivalTime"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Offloading Started" source="loadingTripLeg_id->offloadingStarted"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Offloading Finished" source="loadingTripLeg_id->offloadingCompleted"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Town" source="loadingTripLeg_id->locationFromPoint_id->parent_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loading Point" source="loadingTripLeg_id->locationFromPoint_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Location To Town" source="loadingTripLeg_id->locationToPoint_id->parent_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Offloading Point" source="loadingTripLeg_id->locationToPoint_id"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Kms Begin" source="loadingTripLeg_id->kmsBegin"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Kms End" source="loadingTripLeg_id->kmsEnd"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Loaded Kms" source="loadingTripLeg_id->actualKms"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Tons Actual" source="tonsActual"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Gross Vehicle Mass" source="offloadingWeighGrossMass"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Truck FM" source="loadingTripLeg_id->truck_id->fM"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Blackout Status" source="loadingTripLeg_id->truck_id->isBlackout"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Province" source="loadingTripLeg_id->locationToPoint_id->parent_id->parent_id->name"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Product Category" source="productCategory_id->name"
clia $TENANT_ID DataView addField objectRegistry=udo_Cargo type=ItemListDataView name="Incomplete Trips by Fleet" label="Product Type" source="productType_id->name"
clia $TENANT_ID Report create name="Incomplete Trips by Fleet" objectRegistry="udo_Cargo" dataView="Incomplete Trips by Fleet" dataViewType="ItemListDataView" primaryOwner="Admin" primaryOwnerCrud="Create, Read, Update, Delete" groupOwner="Reports" groupOwnerCrud="Read"
clia $TENANT_ID Report setInterimDataView name="Incomplete Trips by Fleet" objectRegistry=DateRangeValue dataViewName="Trucks in a Fleet" type=ItemListDataView


